name: e_tikbroh_yok
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+24

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#  getX ^4.6.5
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.6

#  get file,compres image and crop image
  file_picker: ^5.3.0
  image_picker: ^0.8.7+5
  flutter_image_compress: ^2.0.3
  image_cropper: ^4.0.1

#  google map
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2

#  firebase notification
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0

#  image slide
  carousel_slider: ^4.2.1

#  video player
  youtube_player_flutter: ^8.1.2

# lainnya
  intl: ^0.18.1
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  image_preview: ^1.0.4
  badges: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  # example:
  fonts:
    - family: FutureReguler
      fonts:
        - asset: assets/fonts/future/future_reguler.ttf
    - family: FutureBold
      fonts:
        - asset: assets/fonts/future/future_bold.ttf
    - family: OpenSansReguler
      fonts:
        - asset: assets/fonts/open_sans/open_sans_reguler.ttf
    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/open_sans/open_sans_bold_italic.ttf
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf


